# Github action for testing autograde on each commit/pr

name: test autograde

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install autograde
      run: |
        python -m pip install --upgrade pip
        pip install -e .[develop]
    - name: Lint with flake8
      run: |
        # stop the build if there are syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # warn for all other errors
        flake8 . --count --exit-zero --statistics
    - name: Test with nose
      run: |
        pip install nose
        python -m nose