# Github action for testing autograde on each commit/pr

name: test autograde

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install autograde
      run: |
        python -m pip install --upgrade pip
        pip install -e .[develop]
    - name: Test with nose
      run: |
        pip install nose
        python -m nose
